version: 2.1
jobs:
  build:
    docker:
      - image: alpine
    working_directory: ~/default-values-spike
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            echo 'In the command...'
            ls -a
            ./pp-default-values-alerting