version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: ~/default-values-spike
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            RUN apt-get update && apt-get install -y
            apt install curl -y
            echo 'In the command...'
            ls -a
            ./pp-default-values-alerting.sh