version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: ruby
    working_directory: ~/default-values-spike
    steps:
      - checkout
      - run:
          name: Install bundler
          command: |
            echo 'Installing bundler...'
            gem install bundler
      - run:
          name: Bundle Install
          command: |
            echo 'Bundling'
            bundle install
      - run:
          name: Run tests
          environment:
            RESULT: ruby default_content_finder.rb
          command: |
            echo 'Running Ruby script'
            echo "${RESULT}"
      - slack/status:
          fail_only: true 