version: 2.1
jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            echo 'In the command...'
            bash pp-default-values-alerting.sh 