version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu
    working_directory: ~/default-values-spike
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            apt-get update && \
              apt-get -y install sudo
            sudo apt install curl
            echo 'In the command...'
            ls -a
            ./pp-default-values-alerting.sh