version: 2.1
orbs:
  slack: circleci/slack@3.4.2
jobs:
  build:
    docker:
      - image: ruby
    working_directory: ~/default-values-spike
    steps:
      - checkout
      - run:
          name: Install bundler
          command: |
            echo 'Installing bundler...'
            gem install bundler
      - run:
          name: Bundle Install
          command: |
            echo 'Bundling'
            bundle install
      - run:
          name: Run tests
          command: |
            echo 'Running Ruby script'
            RESULT=$(ruby default_content_finder.rb)
            echo $RESULT
            echo 'export SHARED_RESULT="$(ruby default_content_finder.rb)"' >> $BASH_ENV
            echo $BASH_ENV
      - slack/status:
          fail_only: true 
          failure_message: 'Does this even work'